# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target '' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for the project
  pod 'Firebase/Analytics'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITests' do
    # Pods for testing
  end

end
